---
title: "Ricordati passi fondamentali della procedura DD"
format: pdf
editor: visual
---

## Scadenze fondamentali:

-   fine APRILE :: comunicazione ricevuta degli studenti INCOMING selezionati da ENSAI

-   accettazione delle candidature, previa verifica e successivo trasferimento delle informazioni all'ufficio preposto alla gestione degli studenti di doppio titolo \<doubledegree.sapienza\@uniroma1.it\> (Antonella Fabbricatore) che provvederà a comunicare agli studenti le modalità per l'ammissione ed inserire i sloro dati nel sistema INFOSTUD in modo da dotare ciascuno studente ammesso di matricola e, possibilmente, di indirizzo email Sapienza con il quale accreditarsi presso tutti i servizi Sapienza sin dall'inizio.

-   comunicazione agli studenti sulle informazioni da inserire in autonomia nel sistema INFOSTUD e documentazione da fornire per il primo processo di **immatricolazione** come studenti di **laurea triennale**. Ricordiamoci che abbiamo già dei fac-simile presso il seguente indirizzo: <https://bit.ly/SMA-document-for-enrolment-table>

-   fissare una scadenza per gli studenti affinché possano ricevere un eventuale feedback da parte nostra circa l'idoneità dei documenti. In tal caso è necessario che l'Ufficio Studenti Stranieri [studentistranieri\@uniroma1.it](mailto:studentistranieri@uniroma1.it){.email} si esprima a riguardo. Proviamo a fissare la data al **20 giugno**?

-   entro max il **31 luglio 2026** - **delibera del CdS SESS** per iscrizione al **terzo anno** con **riconoscimento 174 crediti**. In realtà potremmo anche tentare nella sessione precedente fissando la scadenza per la delibera lo stesso 20 giugno laddove i crediti del II semestre ad ENSAI siano stati acquisiti. La scadenza per la presentazione della domanda di laurea triennale sarebbe in tal caso il **24 giugno**. Altrimenti la successiva sarebbe il **20 settembre**.

-   
